### ISSUE TITLE
ready for release?

### ISSUE THREAD

**Issue by psifertex** [elbiazo/calltree#1]
Would love to get this in the plugin manager -- anything you're looking to finish before doing a release?

**Comment by elbiazo** [comment]
Let me get some screenshots added, and I will submit a pull request today!

**Comment by psifertex** [comment]
Just close this out when you do -- no need to submit directly to the plugin manager repo when you do the release.

**Comment by elbiazo** [comment]
done

**Comment by psifertex** [comment]
I don't see a release? https://github.com/elbiazo/calltree/releases

Please see: https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release

**Comment by elbiazo** [comment]
sorry there should be an release now
