### ISSUE TITLE
Long function names expand sidebar, prevent shrinking it

### ISSUE THREAD

**Issue by galenbwill** [elbiazo/calltree#4]
![image](https://user-images.githubusercontent.com/12259536/153531108-3c2ccc5b-fc37-4841-9bbb-5dbf497a89ad.png)

When the name of the selected function is too long, the sidebar gets expanded to fit it, and the sidebar cannot be resized smaller until a shorter-named function is selected.

**Comment by elbiazo** [comment]
Thank for the issue. Been great help 👍
