### ISSUE TITLE
handle name mangling

### ISSUE THREAD

**Issue by elbiazo** [elbiazo/calltree#9]
It seems like when you do current_function.name on mangled name. It does not really give you unmangled name. Binja somehow demangles it on their UI so fix this.

![image](https://user-images.githubusercontent.com/23147879/160255464-e8eb53aa-e5dc-4d14-8cb9-b808e5d06b1f.png)

**Comment by droogie** [comment]
If you can expose bv to obtain the arch when updating the names you can try something like this

```python
def demangle_name(function_name):
    ms = demangle_ms(bv.arch, function_name)
    gnu = demangle_gnu3(bv.arch, function_name)
    
    if (ms[0] != None):
        #return("::".join(str(n) for n in ms[1]))
        return get_qualified_name(ms[1])
    elif (gnu[0] != None):
        #return("::".join(str(n) for n in gnu[1]))
        return get_qualified_name(gnu[1])
    else:
        return(function_name)

print(demangle_name("?testf@Foobar@@SA?AW4foo@1@W421@@Z"))
print(demangle_name("_ZN6google8protobuf8internal14WireFormatLite11WriteUInt32EijPNS0_2io17CodedOutputStreamE"))
```

```
Foobar::testf
google::protobuf::internal::WireFormatLite::WriteUInt32
```

**Comment by droogie** [comment]
Yea, seems to be the same solution others have used, https://github.com/Shizmob/binja-depanalyzer/blob/5b469620ca7e0d9eb5f615578a1d89c22fc4b047/util.py#L9
